<?php 
// $Id: linkit_permissions.module,v 1.1.2.1 2010/08/27 16:56:03 anon Exp $

/**
 * @file
 * Extend Linkit with permissions.
 */

/**
 * Implementation of hook_perm().
 */
function linkit_permissions_perm() {
  $perms = array('create all links');
  foreach (module_invoke_all('linkit_info_plugins') as $plugin) {
    $perms[] = 'create '. check_plain($plugin['type']) .' links';
  }
  return $perms;
}